---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: python:3.6
  commands:
  - python3 setup.py sdist bdist_wheel
  volumes:
  - name: artifacts
    path: /tmp/artifacts

- name: pypi
  image: plugins/pypi
  settings:
    distributions:
    - sdist
    - bdist_wheel
    password:
      from_secret: pypi-secret
    username: nikitanovosibirsk
  volumes:
  - name: artifacts
    path: /tmp/artifacts

volumes:
- name: artifacts
  temp: {}

trigger:
  event:
  - tag
  status:
  - success

...
